config/routes.rb
Rails.application.routes.draw do

  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  get 'searches/search'
  devise_for :shop, controllers: {
    sessions: 'restaurant/sessions',
    passwards: 'restaurant/passwards',
    registrations: 'restaurant/registrations'
  }

  devise_for :customer, controllers: {
    sessions: 'public/sessions',
    passwards: 'public/passwards',
    registrations: 'public/registrations'
  }

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwards: 'admin/passwards',
    registrations: 'admin/registrations'
  }

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
        get :favorite
      end
    end
    resources :shops, only: [:show, :index] do
      resource :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      resources :menus, only: [:index, :show]
      resources :seats, only: [:index, :show]
      resources :images, only: [:index, :show]
    end
  end

  namespace :restaurant do
    get "/about" => "homes#about", as: "about"
    resource :shops, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
    resources :menus, only: [:create, :new, :index, :show, :edit, :update]
    resources :seats, only: [:create, :new, :index, :edit, :update, :show]
    resources :images, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index]
    resources :shops, only: [:index]
  end

  get "search" => "searches#search"

  get 'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

end

app/models/shop.rb
class Shop < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :menus, dependent: :destroy
  has_many :seats, dependent: :destroy
  has_many :images, dependent: :destroy

  validates :shop_name, presence: true
  validates :shop_name_kana, presence: true

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

  enum reserve: { reserve_only: 0, reserve_possible: 1, reserve_impossible: 2 }

  attachment :image


  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @shops = Shop.page(params[:page]).per(10).order("id DESC")
  end
end

app/controllers/restaurant/confirmations_controller.rb
# frozen_string_literal: true

class Restaurant::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/restaurant/homes_controller.rb
class Restaurant::HomesController < ApplicationController
  def about
  end
end

app/controllers/restaurant/images_controller.rb
class Restaurant::ImagesController < ApplicationController

  before_action :authenticate_shop!

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @image.shop_id = current_shop.id
    if @image.save
      redirect_to restaurant_images_path
    else
      render :new
    end
  end

  def index
    @images = current_shop.images.page(params[:page]).per(20).order("id DESC")
  end

  def show
    @image = Image.find(params[:id])
  end

  def edit
    @image = Image.find(params[:id])
    if @image.shop != current_shop
      redirect_to new_shop_session_path
    end
  end

  def update
    @image = Image.find(params[:id])
    @image.shop_id = current_shop.id
    if @image.update(image_params)
      redirect_to restaurant_image_path(@image.id)
    else
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to restaurant_images_path
  end

  private

  def image_params
    params.require(:image).permit(:image, :shop_id, :introduction)
  end
end

app/controllers/restaurant/menus_controller.rb
class Restaurant::MenusController < ApplicationController

  before_action :authenticate_shop!

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.shop_id = current_shop.id
    if  @menu.save
      redirect_to restaurant_menu_path(@menu)
    else
      render :new
    end
  end

  def index
    @menus = current_shop.menus.page(params[:page]).per(20).order("id DESC")
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def edit
    @menu = Menu.find(params[:id])
    if @menu.shop != current_shop
      redirect_to new_shop_session_path
    end
  end

  def update
    @menu = Menu.find(params[:id])
    if @menu.update(menu_params)
      redirect_to restaurant_menu_path(@menu)
    else
      render :edit
    end
  end

  private

  def menu_params
    params.require(:menu).permit(:shop_id, :name, :image, :price, :is_active)
  end
end

app/controllers/restaurant/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Restaurant::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/restaurant/passwords_controller.rb
# frozen_string_literal: true

class Restaurant::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/restaurant/registrations_controller.rb
# frozen_string_literal: true

class Restaurant::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  def after_sign_in_path_for(resource)
    restaurant_shops_path
  end

  def after_sign_out_path_for(resource)
    restaurant_about_path
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :email, :encrypted_password, :shop_name, :shop_name_kana, :postal_code, :address, :telephone_number, :opening_hours, :holiday, :introduction, :image, :genre, :reserve, :parking_space, :payment_method, :smoking, :private_room, :ticket, :children, :wait_time, :access, :is_deleted])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/restaurant/seats_controller.rb
class Restaurant::SeatsController < ApplicationController

  before_action :authenticate_shop!

  def new
    @seat = Seat.new
  end

  def create
    @seat = Seat.new(seat_params)
    @seat.shop_id = current_shop.id
    if @seat.save
      redirect_to restaurant_seats_path
    else
      render :new
    end
  end

  def index
    @seats = current_shop.seats
  end
  
  def show
    @seat = Seat.find(params[:id])
  end

  def edit
    @seat = Seat.find(params[:id])
    if @seat.shop != current_shop
      redirect_to new_shop_session_path
    end
  end

  def update
    @seat = Seat.find(params[:id])
    if @seat.update(seat_params)
      redirect_to restaurant_seats_path
    else
      render :edit
    end
  end

  def seat_params
    params.require(:seat).permit(:seat_type, :image, :introduction, :people, :smoking, :reserve, :is_active, :shop_id)
  end
end

app/controllers/restaurant/sessions_controller.rb
# frozen_string_literal: true

class Restaurant::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
    restaurant_shops_path
  end

  def after_sign_out_path_for(resource)
    restaurant_about_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_user
    @shop = Shop.find_by(email: params[:shop][:email].downcase)
    if @shop
      if (@customer.valid_password?(params[:shop][:password]) && (@shop.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_shop_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/restaurant/shops_controller.rb
class Restaurant::ShopsController < ApplicationController

   before_action :authenticate_shop!

  def show
    @shop = current_shop
    @comment = Comment.new
  end

  def edit
    @shop = current_shop
  end

  def update
    @shop = current_shop
    if @shop.update(shop_params)
      redirect_to restaurant_shops_path
    else 
      render :edit
    end
  end

  def unsubscribe
  end

  def withdraw
    @shop = current_shop
    @shop.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def shop_params
    params.require(:shop).permit(:email, :shop_name, :shop_name_kana, :postal_code, :address, :telephone_number, :opening_hours, :holiday, :introduction, :image, :genre, :reserve, :parking_space, :payment_method, :smoking, :private_room, :ticket, :children, :wait_time, :access, :is_deleted)
  end

end

app/controllers/restaurant/unlocks_controller.rb
# frozen_string_literal: true

class Restaurant::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/restaurant/homes_helper.rb
module Restaurant::HomesHelper
end

app/helpers/restaurant/images_helper.rb
module Restaurant::ImagesHelper
end

app/helpers/restaurant/menus_helper.rb
module Restaurant::MenusHelper
end

app/helpers/restaurant/seats_helper.rb
module Restaurant::SeatsHelper
end

app/helpers/restaurant/shops_helper.rb
module Restaurant::ShopsHelper
end

app/views/restaurant/shops/edit.html.erb
<div class="container pb-5 mb-5">
  <div class="row">
    <h4 class="mt-5 ml-4">お店の情報を編集</h4>
    <p></p>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= form_with model:@shop, url: restaurant_shops_path, local:true do |f| %>
      <% if @shop.errors.any? %>
        <% @shop.errors.full_messages.each do |message| %>
          <div class="text-danger">
            ※<%= message %>
          </div>
        <% end %>
      <% end %>
      <form>
        <div class="form-group mt-3">
          <label for="shop_name">店名</label><span class="text-danger">(必須)</span>
          <%= f.text_field :shop_name, autofocus: true, class: "form-control" %>
        </div>

      <div class="form-group mt-4">
        <label for="shop_name_kana">店名フリガナ</label><span class="text-danger">(必須)</span>
        <%= f.text_field :shop_name_kana, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-growp mt-4">
        <label for="image">イメージ画像</label>
        <div class="image">
          <%= f.attachment_field :image %>
        </div>
      </div>

      <div class="form-growp mt-4">
        <label for="email">メールアドレス</label><span class="text-danger">(必須)</span>
        <%= f.email_field :email, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-growp mt-4">
        <label for="telephone_number">電話番号(ハイフンなし)</label>
        <%= f.text_field :telephone_number, autofocus: true, class: "form-control" %>
      </div>
      <div class="form-growp mt-4">
        <label for="postal_code">郵便番号(ハイフンなし)</label>
        <%= f.text_field :postal_code, autofocus: true, class: "form-control" %>
      </div>
      <div class="form-growp mt-4">
        <label for="address">住所</label>
        <%= f.text_field :address, autofocus: true, class: "form-control" %>
      </div>
      <div class="form-growp mt-4">
        <label for="accsee">最寄り駅</label>
        <%= f.text_area :access, autofocus: true, class: "form-control" %>
      </div>
      <div class="form-growp mt-4">
        <label for="opening_hours">営業時間</label>
        <%= f.text_area :opening_hours, autofocus: true, class: "form-control" %>
      </div>
      <div class="form-growp mt-4">
        <label for="holiday">定休日</label>
        <%= f.text_area :holiday, autofocus: true, class: "form-control" %>
      </div>
      <div class="form-growp mt-4">
        <label for="genre">ジャンル</label>
        <%= f.text_field :genre, autofocus: true, class: "form-control" %>
      </div>
      <div class="form-growp mt-4">
        <label for="reserve">予約</label>
        <div class="reserve">
          <%= f.radio_button :reserve, "reserve_only" %>
          <%= f.label :reserve, "完全予約制" %>
          <%= f.radio_button :reserve, "reserve_possible" %>
          <%= f.label :reserve, "予約可" %>
          <%= f.radio_button :reserve, "reserve_impossible" %>
          <%= f.label :reserve, "予約不可" %>
        </div>
      </div>
      <div class="form-growp mt-4">
        <label for="payment_method">支払方法</label>
        <%= f.text_area :payment_method, autofocus: true, class: "form-control" %>
      </div>
      <div class="form-growp mt-4">
        <label for="parking_space">駐車場</label>
        <%= f.select :parking_space, *[0..50] %>台有
      </div>

      <div class="form-growp mt-4">
        <label for="smoking">禁煙喫煙</label>
        <%= f.text_area :smoking, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-growp mt-4">
        <label for="private_room">個室有無</label>
        <div class="private_room">
          <%= f.radio_button :private_room, :true %>
          <%= f.label :private_room, "個室有", value: true %>
          <%= f.radio_button :private_room, :false %>
          <%= f.label :private_room, "個室無", value: false %>
        </div>
      </div>
      <div class="form-growp mt-4">
        <label for="ticket">整理券有無</label>
        <div class="ticket">
          <%= f.radio_button :ticket, :true %>
          <%= f.label :ticket, "配布有", value: true %>
          <%= f.radio_button :ticket, :false %>
          <%= f.label :ticket, "配布無", value: false %>
        </div>
      </div>
      <div class="form-growp mt-4">
        <label for="children">子連れ可否</label>
        <%= f.text_area :children, autofocus: true, class: "form-control" %>
      </div>
      <div class="form-growp mt-4">
        <label for="wait_time">通常待ち時間</label>
        <%= f.text_area :wait_time, autofocus: true, class: "form-control" %>
      </div>
      <div class="form-growp mt-4">
        <label for="introduction">紹介文</label>
        <%= f.text_area :introduction, autfocus: true, class: "form-control" %>
      </div>
      <div class="form-growp mt-4">
        <%= link_to "戻る", restaurant_shops_path %><br>
        <%= f.submit "内容を変更する", class: "btn btn-outline-secondary" %>
        <div class="mt-4">
          <%= link_to "退会する", unsubscribe_restaurant_shops_path, class: "btn btn-outline-secondary" %>
        </div>
      </div>
    </form>
    <% end %>

    </div>
  </div>
</div>

app/views/restaurant/shops/show.html.erb
<div class="container mt-4 mb-5">
  <div class="row">
    <h4><%= @shop.shop_name %></h4>
  </div>
  <div class="row">
    <%= @shop.shop_name_kana %>
  </div>
  <div class="row">
    <div class="col-md-4">
      <h5><i class="fas fa-heart"></i><%= @shop.favorites.count %></h5>
    </div>
    <div class="col-md-2">

    </div>
  </div>
  <div class="row mt-4">
    <div class="mx-auto">
       <%= attachment_image_tag @shop, :image, :fill, 400, 300, format: 'jpeg', class: "rounded" %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-md-10 offset-md-1">
      <%= link_to "Menu List", restaurant_menus_path, class: "btn btn-outline-warning" %>
      <%= link_to "Menu新規登録", new_restaurant_menu_path, class: "btn btn-outline-warning" %>
      <%= link_to "席タイプ", restaurant_seats_path, class: "btn btn-outline-warning" %>
      <%= link_to "席タイプ新規登録", new_restaurant_seat_path, class: "btn btn-outline-warning" %>
      <%= link_to "Photo", restaurant_images_path, class: "btn btn-outline-warning" %>
      <%= link_to "Photo新規投稿", new_restaurant_image_path, class: "btn btn-outline-warning" %>
      <%= link_to "基本情報を編集する", edit_restaurant_shops_path, class: "btn btn-outline-warning" %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-md-7">
      <span class="badge badge-secondary">
        <h5><i class="fas fa-info-circle"></i>基本情報</h5>
      </span>
      <table class="table table-borderless">
        <tbody>
        <tr>
          <th scope="row">電話番号</th>
          <td><%= @shop.telephone_number %></td>
        </tr>
        <tr>
          <th scope="row">営業時間</th>
          <td><%= @shop.opening_hours %></td>
        </tr>
        <tr>
          <th scope="row">定休日</th>
          <td><%= @shop.holiday %></td>
        </tr>
        <tr>
          <th scope="row">住所</th>
          <td>
            〒<%= @shop.postal_code %><br>
            <%= @shop.address %>
          </td>
        </tr>
        <tr>
          <th scope="row">アクセス</th>
          <td><%= @shop.access %></td>
        </tr>
        <tr>
          <th scope="row">ジャンル</th>
          <td><%= @shop.genre %></td>
        </tr>
        <tr>
          <th scope="row">予約可否</th>
          <td><%= @shop.reserve_i18n %></td>
        </tr>
        <tr>
          <th scope="row">駐車スペース</th>
          <td><%= @shop.parking_space %>台</td>
        </tr>
        <tr>
          <th scope="row">支払方法</th>
          <td><%= @shop.payment_method %></td>
        </tr>
        <tr>
          <th scope="row">喫煙禁煙</th>
          <td><%= @shop.smoking %></td>
        </tr>
        <tr>
          <th scope="row">個室有無</th>
          <td>
            <% if @shop.private_room == true %>
              有
            <% else %>
              無
            <% end %>
          </td>
        </tr>
        <tr>
          <th scope="row">整理券配布有無</th>
          <td>
            <% if @shop.private_room == true %>
              有
            <% else %>
              無
            <% end %>
          </td>
        </tr>
        <tr>
          <th scope="row">子連れ可否</th>
          <td><%= @shop.children %></td>
        </tr>
        <tr>
          <th scope="row">通常混雑状況</th>
          <td><%= @shop.wait_time %></td>
        </tr>
        <tr>
          <th scope="row">メッセージ</th>
          <td><%= @shop.introduction %></td>
        </tr>
      </tbody>
      </table>
    </div>
    <div class="col-md-5">
      <span class="badge badge-secondary">
        <h5><i class="far fa-comment-dots"></i>コメント</h5>
      </span>
      <h6>コメント: <%= @shop.comments.count %>件</h6>
      <% @shop.comments.each do |comment| %>
      <div class="card mt-3">
        <div class="card-header">
          <h5><%= comment.customer.last_name %><%= comment.customer.first_name %></h5>
          <p class="card-text"><%= comment.created_at.strftime('%Y.%m.%d %H:%M') %></p>
        </div>
        <div class="card-body">
          <strong class="card-text"><%= comment.comment %></strong>
          <div id="rate_<%= comment.id %>"></div>
          <script>
            $('#rate_<%= comment.id %>').empty();
            $('#rate_<%= comment.id %>').raty({
              readOnly: true,
              score: "<%= comment.rate %>",
              size: 36,
              starOff: "<%= asset_path('star-off.png') %>",
              starOn: "<%= asset_path('star-on.png') %>",
            });
          </script>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="row">

  </div>
</div>

app/views/restaurant/shops/unsubscribe.html.erb
<div class="container pb-5 mb-5">
  <div class="row">
    <h4 class="mt-5 ml-4">退会処理画面</h4>
  </div>
  <div class="row mt-5">
    <div class="mx-auto">
      <h4>
        退会すると、お店の情報を公開できなくなります。
      </h4>
    </div>
  </div>

  <div class="row mt-4 pt-5">
    <div class="mx-auto">
      <%= link_to "退会しない", restaurant_shops_path, class: "btn btn-outline-secondary" %><br>
    </div>
  </div>
  <div class="row mt-4">
    <div class="mx-auto">
      <%= link_to "退会する", withdraw_restaurant_shops_path, method: :patch, "data-confirm" => "本当に退会しますか?", class: "btn btn-outline-danger" %>
    </div>
  </div>
</div>