config/routes.rb
Rails.application.routes.draw do

  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  get 'searches/search'
  devise_for :shop, controllers: {
    sessions: 'restaurant/sessions',
    passwards: 'restaurant/passwards',
    registrations: 'restaurant/registrations'
  }

  devise_for :customer, controllers: {
    sessions: 'public/sessions',
    passwards: 'public/passwards',
    registrations: 'public/registrations'
  }

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwards: 'admin/passwards',
    registrations: 'admin/registrations'
  }

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
        get :favorite
      end
    end
    resources :shops, only: [:show, :index] do
      resource :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      resources :menus, only: [:index, :show]
      resources :seats, only: [:index, :show]
      resources :images, only: [:index, :show]
    end
  end

  namespace :restaurant do
    get "/about" => "homes#about", as: "about"
    resource :shops, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
    resources :menus, only: [:create, :new, :index, :show, :edit, :update]
    resources :seats, only: [:create, :new, :index, :edit, :update, :show]
    resources :images, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index]
    resources :shops, only: [:index]
  end

  get "search" => "searches#search"

  get 'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

end

app/models/menu.rb
class Menu < ApplicationRecord

  belongs_to :shop

  attachment :image

  validates :name, presence: true
  validates :price, presence: true

  def add_tax_price
    (self.price * 1.10).round
  end
end

app/controllers/restaurant/confirmations_controller.rb
# frozen_string_literal: true

class Restaurant::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/restaurant/homes_controller.rb
class Restaurant::HomesController < ApplicationController
  def about
  end
end

app/controllers/restaurant/images_controller.rb
class Restaurant::ImagesController < ApplicationController

  before_action :authenticate_shop!

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @image.shop_id = current_shop.id
    if @image.save
      redirect_to restaurant_images_path
    else
      render :new
    end
  end

  def index
    @images = current_shop.images.page(params[:page]).per(20).order("id DESC")
  end

  def show
    @image = Image.find(params[:id])
  end

  def edit
    @image = Image.find(params[:id])
    if @image.shop != current_shop
      redirect_to new_shop_session_path
    end
  end

  def update
    @image = Image.find(params[:id])
    @image.shop_id = current_shop.id
    if @image.update(image_params)
      redirect_to restaurant_image_path(@image.id)
    else
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to restaurant_images_path
  end

  private

  def image_params
    params.require(:image).permit(:image, :shop_id, :introduction)
  end
end

app/controllers/restaurant/menus_controller.rb
class Restaurant::MenusController < ApplicationController

  before_action :authenticate_shop!

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.shop_id = current_shop.id
    if  @menu.save
      redirect_to restaurant_menu_path(@menu)
    else
      render :new
    end
  end

  def index
    @menus = current_shop.menus.page(params[:page]).per(20).order("id DESC")
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def edit
    @menu = Menu.find(params[:id])
    if @menu.shop != current_shop
      redirect_to new_shop_session_path
    end
  end

  def update
    @menu = Menu.find(params[:id])
    if @menu.update(menu_params)
      redirect_to restaurant_menu_path(@menu)
    else
      render :edit
    end
  end

  private

  def menu_params
    params.require(:menu).permit(:shop_id, :name, :image, :price, :is_active)
  end
end

app/controllers/restaurant/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Restaurant::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/restaurant/passwords_controller.rb
# frozen_string_literal: true

class Restaurant::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/restaurant/registrations_controller.rb
# frozen_string_literal: true

class Restaurant::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  def after_sign_in_path_for(resource)
    restaurant_shops_path
  end

  def after_sign_out_path_for(resource)
    restaurant_about_path
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :email, :encrypted_password, :shop_name, :shop_name_kana, :postal_code, :address, :telephone_number, :opening_hours, :holiday, :introduction, :image, :genre, :reserve, :parking_space, :payment_method, :smoking, :private_room, :ticket, :children, :wait_time, :access, :is_deleted])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/restaurant/seats_controller.rb
class Restaurant::SeatsController < ApplicationController

  before_action :authenticate_shop!

  def new
    @seat = Seat.new
  end

  def create
    @seat = Seat.new(seat_params)
    @seat.shop_id = current_shop.id
    if @seat.save
      redirect_to restaurant_seats_path
    else
      render :new
    end
  end

  def index
    @seats = current_shop.seats
  end
  
  def show
    @seat = Seat.find(params[:id])
  end

  def edit
    @seat = Seat.find(params[:id])
    if @seat.shop != current_shop
      redirect_to new_shop_session_path
    end
  end

  def update
    @seat = Seat.find(params[:id])
    if @seat.update(seat_params)
      redirect_to restaurant_seats_path
    else
      render :edit
    end
  end

  def seat_params
    params.require(:seat).permit(:seat_type, :image, :introduction, :people, :smoking, :reserve, :is_active, :shop_id)
  end
end

app/controllers/restaurant/sessions_controller.rb
# frozen_string_literal: true

class Restaurant::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
    restaurant_shops_path
  end

  def after_sign_out_path_for(resource)
    restaurant_about_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_user
    @shop = Shop.find_by(email: params[:shop][:email].downcase)
    if @shop
      if (@customer.valid_password?(params[:shop][:password]) && (@shop.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_shop_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/restaurant/shops_controller.rb
class Restaurant::ShopsController < ApplicationController

   before_action :authenticate_shop!

  def show
    @shop = current_shop
    @comment = Comment.new
  end

  def edit
    @shop = current_shop
  end

  def update
    @shop = current_shop
    if @shop.update(shop_params)
      redirect_to restaurant_shops_path
    else 
      render :edit
    end
  end

  def unsubscribe
  end

  def withdraw
    @shop = current_shop
    @shop.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def shop_params
    params.require(:shop).permit(:email, :shop_name, :shop_name_kana, :postal_code, :address, :telephone_number, :opening_hours, :holiday, :introduction, :image, :genre, :reserve, :parking_space, :payment_method, :smoking, :private_room, :ticket, :children, :wait_time, :access, :is_deleted)
  end

end

app/controllers/restaurant/unlocks_controller.rb
# frozen_string_literal: true

class Restaurant::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/restaurant/homes_helper.rb
module Restaurant::HomesHelper
end

app/helpers/restaurant/images_helper.rb
module Restaurant::ImagesHelper
end

app/helpers/restaurant/menus_helper.rb
module Restaurant::MenusHelper
end

app/helpers/restaurant/seats_helper.rb
module Restaurant::SeatsHelper
end

app/helpers/restaurant/shops_helper.rb
module Restaurant::ShopsHelper
end

app/views/restaurant/menus/edit.html.erb
<div class="container mb-5 pb-5">
  <div class="row">
    <h4 class="mt-5 ml-4">メニュー編集</h4>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= form_with model:@menu, url: restaurant_menu_path(@menu.id), local:true do |f| %>
      <% if @menu.errors.any? %>
          <% @menu.errors.full_messages.each do |message| %>
            <div class="text-danger">
              ※<%= message %>
            </div>
          <% end %>
        <% end %>
        <form>
          <div class="form-growp mt-3">
            <label for="name">メニュー名</label><span class="text-danger">(必須)</span>
            <%= f.text_field :name, autofocus: true, class: "form-control" %>
          </div>
          <div class="form-growp mt-5">
            <label for="image">イメージ画像</label>
            <%= f.attachment_field :image %>
          </div>
          <div class="form-growp mt-5">
            <label for="price">値段</label><span class="text-danger">(必須)</span>
            <%= f.text_field :price, autofocus: true, class: "form-control" %>
          </div>
          <div class="form-growp mt-5">
            <label for="status">販売ステータス</label>
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "販売中", value: true %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "販売停止中", value: false %>
          </div>
          <div class="form-growp mt-5">
            <%= f.submit "変更する", class: "btn btn-outline-secondary" %>
          </div>
          <div class="form-growp mt-4">
            <%= link_to "他のメニューを見る", restaurant_menus_path %><br>
            <%= link_to "マイページに戻る", restaurant_shops_path %><br>
            <%= link_to "戻る", restaurant_menu_path(@menu.id) %>
          </div>
        </form>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurant/menus/index.html.erb
<div class="container mb-5 pb-5">
  <div class="row">
    <h4 class="mt-4">メニュー 一覧</h4>
    <h3 class="ml-4 mt-3">
      <%= link_to new_restaurant_menu_path, class: "nav-link text-dark" do %>
        <i class="far fa-plus-square"></i>
      <% end %>
    </h3>
  </div>
  <div class="row">
    <p>メニュー数：<%= @menus.count %></p>
  </div>
  <div class="row">
    <%= link_to "マイページに戻る", restaurant_shops_path %>
  </div>
  <div class="row mt-5">
    <% @menus.each do |menu| %>
      <div class="d-flex justify-content-start ml-3 mb-3">
        <div class="col-auto">
          <%= link_to restaurant_menu_path(menu.id), class: "text-dark nav-link" do %>
          <div class="image">
            <%= attachment_image_tag menu, :image, :fill, 200, 190, format: 'jpeg', class: "rounded" %>
          </div>
          <h6 class="mt-1">
            <%= menu.name %>
          </h6>
          <h6>
            ￥<%= menu.price.to_s(:delimited) %>
          </h6>
          <h6>
            <% if menu.is_active == true %>
              販売中
            <% else %>
            　販売中止中
            <% end %>
          </h6>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= paginate @menus %>
    </div>
  </div>
</div>

app/views/restaurant/menus/new.html.erb
<div class="container mb-5 pb-5">
  <div class="row">
    <h4 class="ml-5 mt-4">メニュー新規登録</h4>
  </div>
  <div class="row">
      <div class="mx-auto">
        <%= form_with model:@menu, url:restaurant_menus_path, local:true do |f| %>
        <% if @menu.errors.any? %>
          <% @menu.errors.full_messages.each do |message| %>
            <div class="text-danger">
              ※<%= message %>
            </div>
          <% end %>
        <% end %>
          <form>
            <div class="form-group mt-3">
              <label for="name">メニュー名</label><span class="text-danger">(必須)</span>
              <%= f.text_field :name, autofocus: true, placeholder: "(例)魚定食", class: "form-control" %>
            </div>
            <div class="form-growp mt-5">
              <label for="image">イメージ画像</label>
              <div class="image">
                <%= f.attachment_field :image %>
              </div>
            </div>
            <div class="form-growp mt-5">
              <label for="price">値段</label><span class="text-danger">(必須)</span>
              <div class="price">
                <%= f.text_field :price, autofocus: true, placeholder: "(例)700", class: "form-control" %>
              </div>
            </div>
            <div class="form-growp mt-5">
              <%= f.submit "登録する", class: "btn btn-outline-secondary" %>
            </div>
            <div class="form-growp mt-4">
              <%= link_to "他のメニューを見る", restaurant_menus_path %><br>
              <%= link_to "マイページに戻る", restaurant_shops_path %>
            </div>
          </form>
        <% end %>
      </div>
  </div>
</div>

app/views/restaurant/menus/show.html.erb
<div class="container mt-5 mb-5 pb-5">
  <div class="row">
    <h4><%= @menu.name %></h4>
  </div>
  <div class="row">
    <%= link_to "メニュー一覧", restaurant_menus_path %>

  </div>
  <div class="row mt-5">
    <div class="col-md-5 offset-md-1">
      <%= attachment_image_tag @menu, :image, :fill, 500, 450, format: 'jpeg', class: "rounded" %>
    </div>

    <div class="col-md-5 offset-md-1">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th scope="row">値段</th>
            <td>
              ￥<%= @menu.price %>(税抜き価格)
            </td>
          </tr>
          <tr>
            <th scope="row">販売状況</th>
            <td>
              <% if @menu.is_active == true %>
                販売中
              <% else %>
              　販売中止中
              <% end %>
            </td>
          </tr>
          <tr>
            <th scope="row"></th>
            <td><%= link_to "編集する", edit_restaurant_menu_path(@menu.id), class: "btn btn-outline-secondary" %></td>
          </tr>
        </tbody>
      </table>
    </div>


  </div>
</div>