config/routes.rb
Rails.application.routes.draw do

  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  get 'searches/search'
  devise_for :shop, controllers: {
    sessions: 'restaurant/sessions',
    passwards: 'restaurant/passwards',
    registrations: 'restaurant/registrations'
  }

  devise_for :customer, controllers: {
    sessions: 'public/sessions',
    passwards: 'public/passwards',
    registrations: 'public/registrations'
  }

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwards: 'admin/passwards',
    registrations: 'admin/registrations'
  }

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
        get :favorite
      end
    end
    resources :shops, only: [:show, :index] do
      resource :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      resources :menus, only: [:index, :show]
      resources :seats, only: [:index, :show]
      resources :images, only: [:index, :show]
    end
  end

  namespace :restaurant do
    get "/about" => "homes#about", as: "about"
    resource :shops, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
    resources :menus, only: [:create, :new, :index, :show, :edit, :update]
    resources :seats, only: [:create, :new, :index, :edit, :update, :show]
    resources :images, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index]
    resources :shops, only: [:index]
  end

  get "search" => "searches#search"

  get 'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :shop

  attachment :image

  validates :image, presence: true

end

app/controllers/restaurant/confirmations_controller.rb
# frozen_string_literal: true

class Restaurant::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/restaurant/homes_controller.rb
class Restaurant::HomesController < ApplicationController
  def about
  end
end

app/controllers/restaurant/images_controller.rb
class Restaurant::ImagesController < ApplicationController

  before_action :authenticate_shop!

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @image.shop_id = current_shop.id
    if @image.save
      redirect_to restaurant_images_path
    else
      render :new
    end
  end

  def index
    @images = current_shop.images.page(params[:page]).per(20).order("id DESC")
  end

  def show
    @image = Image.find(params[:id])
  end

  def edit
    @image = Image.find(params[:id])
    if @image.shop != current_shop
      redirect_to new_shop_session_path
    end
  end

  def update
    @image = Image.find(params[:id])
    @image.shop_id = current_shop.id
    if @image.update(image_params)
      redirect_to restaurant_image_path(@image.id)
    else
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to restaurant_images_path
  end

  private

  def image_params
    params.require(:image).permit(:image, :shop_id, :introduction)
  end
end

app/controllers/restaurant/menus_controller.rb
class Restaurant::MenusController < ApplicationController

  before_action :authenticate_shop!

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.shop_id = current_shop.id
    if  @menu.save
      redirect_to restaurant_menu_path(@menu)
    else
      render :new
    end
  end

  def index
    @menus = current_shop.menus.page(params[:page]).per(20).order("id DESC")
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def edit
    @menu = Menu.find(params[:id])
    if @menu.shop != current_shop
      redirect_to new_shop_session_path
    end
  end

  def update
    @menu = Menu.find(params[:id])
    if @menu.update(menu_params)
      redirect_to restaurant_menu_path(@menu)
    else
      render :edit
    end
  end

  private

  def menu_params
    params.require(:menu).permit(:shop_id, :name, :image, :price, :is_active)
  end
end

app/controllers/restaurant/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Restaurant::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/restaurant/passwords_controller.rb
# frozen_string_literal: true

class Restaurant::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/restaurant/registrations_controller.rb
# frozen_string_literal: true

class Restaurant::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  def after_sign_in_path_for(resource)
    restaurant_shops_path
  end

  def after_sign_out_path_for(resource)
    restaurant_about_path
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :email, :encrypted_password, :shop_name, :shop_name_kana, :postal_code, :address, :telephone_number, :opening_hours, :holiday, :introduction, :image, :genre, :reserve, :parking_space, :payment_method, :smoking, :private_room, :ticket, :children, :wait_time, :access, :is_deleted])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/restaurant/seats_controller.rb
class Restaurant::SeatsController < ApplicationController

  before_action :authenticate_shop!

  def new
    @seat = Seat.new
  end

  def create
    @seat = Seat.new(seat_params)
    @seat.shop_id = current_shop.id
    if @seat.save
      redirect_to restaurant_seats_path
    else
      render :new
    end
  end

  def index
    @seats = current_shop.seats
  end
  
  def show
    @seat = Seat.find(params[:id])
  end

  def edit
    @seat = Seat.find(params[:id])
    if @seat.shop != current_shop
      redirect_to new_shop_session_path
    end
  end

  def update
    @seat = Seat.find(params[:id])
    if @seat.update(seat_params)
      redirect_to restaurant_seats_path
    else
      render :edit
    end
  end

  def seat_params
    params.require(:seat).permit(:seat_type, :image, :introduction, :people, :smoking, :reserve, :is_active, :shop_id)
  end
end

app/controllers/restaurant/sessions_controller.rb
# frozen_string_literal: true

class Restaurant::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
    restaurant_shops_path
  end

  def after_sign_out_path_for(resource)
    restaurant_about_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_user
    @shop = Shop.find_by(email: params[:shop][:email].downcase)
    if @shop
      if (@customer.valid_password?(params[:shop][:password]) && (@shop.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_shop_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/restaurant/shops_controller.rb
class Restaurant::ShopsController < ApplicationController

   before_action :authenticate_shop!

  def show
    @shop = current_shop
    @comment = Comment.new
  end

  def edit
    @shop = current_shop
  end

  def update
    @shop = current_shop
    if @shop.update(shop_params)
      redirect_to restaurant_shops_path
    else 
      render :edit
    end
  end

  def unsubscribe
  end

  def withdraw
    @shop = current_shop
    @shop.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def shop_params
    params.require(:shop).permit(:email, :shop_name, :shop_name_kana, :postal_code, :address, :telephone_number, :opening_hours, :holiday, :introduction, :image, :genre, :reserve, :parking_space, :payment_method, :smoking, :private_room, :ticket, :children, :wait_time, :access, :is_deleted)
  end

end

app/controllers/restaurant/unlocks_controller.rb
# frozen_string_literal: true

class Restaurant::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/restaurant/homes_helper.rb
module Restaurant::HomesHelper
end

app/helpers/restaurant/images_helper.rb
module Restaurant::ImagesHelper
end

app/helpers/restaurant/menus_helper.rb
module Restaurant::MenusHelper
end

app/helpers/restaurant/seats_helper.rb
module Restaurant::SeatsHelper
end

app/helpers/restaurant/shops_helper.rb
module Restaurant::ShopsHelper
end

app/views/restaurant/images/edit.html.erb
<div class="container mb-5 pb-5">
  <div class="row mt-4 ml-4">
    <h4>Photo編集</h4>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= form_with model:@image, url:restaurant_image_path, local: true do |f| %>
      <% if @image.errors.any? %>
        <% @image.errors.full_messages.each do |message| %>
          <div class="text-danger">
            ※<%= message %>
          </div>
        <% end %>
      <% end %>
        <form>
          <div class="form-growp mt-5">
            <label for="image">イメージ画像</label><span class="text-danger">(必須)</span>
            <div class="image">
              <%= f.attachment_field :image %>
            </div>
          </div>
          <div class="form-growp mt-5">
            <label for="introduction">コメント</label>
            <div class="introduction">
              <%= f.text_area :introduction, autofocus: true, placeholder: "(例)お店の外観です", class: "form-control" %>
            </div>
              </div>
            <div class="form-growp mt-5">
              <%= f.submit "保存する", class: "btn btn-outline-secondary" %>
            </div>
            <div class="form-growp mt-2">
              <%= link_to "削除する",restaurant_image_path(@image.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-outline-secondary" %>
            </div>
            <div class="form-growp mt-5">
              <%= link_to "他の投稿を見る", restaurant_images_path %><br>
              <%= link_to "マイページに戻る", restaurant_shops_path %>
            </div>
          </div>
        </form>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurant/images/index.html.erb
<div class="container mb-5 pb-5">
  <div class="row">
    <h4 class="mt-4 ml-4">
      Photos
    </h4>
    <h3 class="ml-4 mt-3">
      <%= link_to new_restaurant_image_path, class: "nav-link text-dark" do %>
        <i class="far fa-plus-square"></i>
      <% end %>
    </h3>
  </div>
  <div class="row ml-4">
    <%= link_to "マイページに戻る", restaurant_shops_path %>
  </div>
  <div class="row mt-4">
    <% @images.each do |image| %>
      <div class="d-flex justify-content-start ml-4 mb-3">
        <div class="col-auto">
          <%= link_to restaurant_image_path(image.id), class: "nav-link text-dark" do %>
          <div class="card" style="width: 12rem;">
            <%= attachment_image_tag image, :image, :fill, 200, 150, format: 'jpeg', class: "card-img-top" %>
            <div class="card-body">
              <p class="card-title"><i class="far fa-comment-dots mr-2"></i><%= image.introduction %></p>
              <p class="card-text"><%= image.created_at.strftime('%Y.%m.%d') %></p>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= paginate @images %>
    </div>
  </div>
</div>

app/views/restaurant/images/new.html.erb
<div class="container mb-5 pb-5">
  <div class="row">
    <h4 class="mt-4 ml-4">Photo　新規登録</h4>
  </div>
  <div class="row">
    <div class="mx-auto">
    <%= form_with model:@image, url:restaurant_images_path, local: true do |f| %>
    <% if @image.errors.any? %>
      <% @image.errors.full_messages.each do |message| %>
        <div class="text-danger">
          ※<%= message %>
        </div>
      <% end %>
    <% end %>
      <form>
        <div class="form-growp mt-5">
          <label for="image">イメージ画像</label><span class="text-danger">(必須)</span>
          <div class="image">
            <%= f.attachment_field :image %>
          </div>
        </div>
        <div class="form-growp mt-5">
          <label for="introduction">コメント</label>
          <div class="introduction">
            <%= f.text_area :introduction, autofocus: true, placeholder: "(例)お店の外観です", class: "form-control" %>
          </div>
            </div>
          <div class="form-growp mt-5">
            <%= f.submit "登録する", class: "btn btn-outline-secondary" %>
          </div>
          <div class="form-growp mt-5">
              <%= link_to "他の投稿を見る", restaurant_images_path %><br>
              <%= link_to "マイページに戻る", restaurant_shops_path %>
            </div>
        </div>
      </form>
    <% end %>
    </div>
  </div>
</div>

app/views/restaurant/images/show.html.erb
<div class="container mb-5 pb-5">
  <div class="row mt-4 mb-4 ml-4">
    <%= link_to "戻る", restaurant_images_path %>
  </div>
  <div class-"row mt-5">
    <div class="col-md-8 offset-md-4">
      <div class="card" style="width: 25rem;">
        <%= attachment_image_tag @image, :image, :fill, 500, 400, format: 'jpeg', class: "card-img-top" %>
        <div class="card-body">
          <p class="card-title"><i class="far fa-comment-dots mr-2"></i><%= @image.introduction %></p>
          <p class="card-text"><%= @image.created_at.strftime('%Y.%m.%d') %></p>
          <p class="card-text"><%= link_to "編集する", edit_restaurant_image_path, class: "badge badge-dark" %></p>
        </div>
      </div>
    </div>
  </div>
</div>