config/routes.rb
Rails.application.routes.draw do

  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  get 'searches/search'
  devise_for :shop, controllers: {
    sessions: 'restaurant/sessions',
    passwards: 'restaurant/passwards',
    registrations: 'restaurant/registrations'
  }

  devise_for :customer, controllers: {
    sessions: 'public/sessions',
    passwards: 'public/passwards',
    registrations: 'public/registrations'
  }

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwards: 'admin/passwards',
    registrations: 'admin/registrations'
  }

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
        get :favorite
      end
    end
    resources :shops, only: [:show, :index] do
      resource :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      resources :menus, only: [:index, :show]
      resources :seats, only: [:index, :show]
      resources :images, only: [:index, :show]
    end
  end

  namespace :restaurant do
    get "/about" => "homes#about", as: "about"
    resource :shops, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
    resources :menus, only: [:create, :new, :index, :show, :edit, :update]
    resources :seats, only: [:create, :new, :index, :edit, :update, :show]
    resources :images, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index]
    resources :shops, only: [:index]
  end

  get "search" => "searches#search"

  get 'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :customer
  belongs_to :shop

  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :favorite_shops, through: :favorites, source: :shop
  has_many :comments, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true


  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :shop
  belongs_to :customer

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :shop

  attachment :image

  validates :image, presence: true

end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message =>'メールアドレスを入力してください'}
end

app/models/menu.rb
class Menu < ApplicationRecord

  belongs_to :shop

  attachment :image

  validates :name, presence: true
  validates :price, presence: true

  def add_tax_price
    (self.price * 1.10).round
  end
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :shop

  validates :seat_type, presence: true
  validates :people, presence: true

  attachment :image
end

app/models/shop.rb
class Shop < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :menus, dependent: :destroy
  has_many :seats, dependent: :destroy
  has_many :images, dependent: :destroy

  validates :shop_name, presence: true
  validates :shop_name_kana, presence: true

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

  enum reserve: { reserve_only: 0, reserve_possible: 1, reserve_impossible: 2 }

  attachment :image


  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    @inquiry = Inquiry.new
    # render :action => 'index'
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    unless @inquiry.valid?
      render :index
    end
  end

  def thanks
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.received_email(@inquiry).deliver
    # render :action => 'thanks'
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    if params[:shop_name].present?
      @shops = Shop.where('shop_name LIKE ?' , "%#{params[:shop_name]}%")
    elsif params[:genre].present?
      @shops = Shop.where('genre LIKE ?', "%#{params[:genre]}%")
    elsif params[:address].present?
      @shops = Shop.where('address LIKE ?', "%#{params[:address]}%")
    else
      @shops = Shop.none
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/restaurant/homes_helper.rb
module Restaurant::HomesHelper
end

app/helpers/restaurant/menus_helper.rb
module Restaurant::MenusHelper
end

app/helpers/restaurant/seats_helper.rb
module Restaurant::SeatsHelper
end

app/helpers/restaurant/shops_helper.rb
module Restaurant::ShopsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/inquiry/confirm.html.erb
<div class="container mt-4 pb-5 mb-5">
<div class="row">
  <h4>お問い合わせ</h4>
</div>

<%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
  <div class="row">
    <div class="col-md-9 offset-md-2">
      <table class="table">
      <tr>
        <th>名前</th>
        <td>
          <%= f.hidden_field :name %>
          <%= @inquiry.name %>
        </td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td>
          <%= f.hidden_field :email %>
          <%= @inquiry.email %>
        </td>
      </tr>
      <tr>
        <th>お問い合わせ内容</th>
        <td>
          <%= f.hidden_field :message %>
          <%= simple_format(@inquiry.message) %>
        </td>
      </tr>
      <tr>
        <th>
          <td>
            <%= f.submit '送信', :class => 'btn btn-outline-secondary' %>
          </td>
        </th>
      </tr>
    </table>
    </div>
  </div>
<% end %>
</div>

app/views/inquiry/index.html.erb
<div class="container mt-5 mb-5 pb-5">
  <div class="row">
    <h4>お問い合わせ</h4>
  </div>
<%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
  <% if @inquiry.errors.any? %>
    <% @inquiry.errors.each do |attr, msg| %>
      <div class="text-danger">
        ※<%= msg %>
      </div>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-9 offset-md-2">
      <table class="table">
        <tr>
          <th>
            名前<span class="text-danger">（必須）</span></th>
          <td>
            <div class="col-md-6">
              <%= f.text_field :name, autfocus: true, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th>メールアドレス<span class="text-danger">（必須）</span></th>
          <td>
            <div class="col-md-6">
              <%= f.text_field :email, autofocus: true, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th>お問い合わせ内容</th>
          <td>
            <div class="col-md-7">
              <%= f.text_area :message, autofocus: true, class: "form-control" %>
            </div>
          </td>
        </tr>
        <tr>
          <th></th>
          <td>
            <%= f.submit '確認', class: 'btn btn-outline-secondary' %>
          </td>
        </tr>
      </table>
    </div>
  </div>
<% end %>

</div>

app/views/inquiry/thanks.html.erb
<div class="container mb-5 pb-5">
  <div class="row mt-5 pt-5">
    <div class="mx-auto">
      <h4>お問い合わせ承りました</h4>
    </div>
  </div>
  <div class="row mt-5">
    <div class="mx-auto">
      <P>
        ご回答まで少々お待ちください
      </P>
    </div>
  </div>
  <div class="row mt-5 pt-5">
    <div class="mx-auto">
      <%= link_to "トップページに戻る" , root_path %>
    </div>
  </div>
</div>